wandb_version: 1

activation:
  value: silu
batch_norm:
  value: false
batch_size:
  value: 64
dropout:
  value: 0.5
epochs:
  value: 30
learning_rate:
  value: 0.1
momentum:
  value: 0.7
num_classes:
  value: 10
optimizer:
  value: sgd_nesterov
seed:
  value: 42
vgg_architecture:
  value:
  - 64
  - 64
  - M
  - 128
  - 128
  - M
weight_decay:
  value: 1.0e-05
