wandb_version: 1

activation:
  value: tanh
batch_norm:
  value: false
batch_size:
  value: 64
dropout:
  value: 0.5
epochs:
  value: 50
learning_rate:
  value: 0.01
momentum:
  value: 0.9
num_classes:
  value: 10
optimizer:
  value: adagrad
seed:
  value: 42
vgg_architecture:
  value:
  - 64
  - 64
  - M
  - 128
  - 128
  - M
weight_decay:
  value: 1.0e-05
