wandb_version: 1

activation:
  value: silu
batch_norm:
  value: true
batch_size:
  value: 64
dropout:
  value: 0.4
epochs:
  value: 20
learning_rate:
  value: 0.0001
momentum:
  value: 0.9
num_classes:
  value: 10
optimizer:
  value: sgd_nesterov
seed:
  value: 42
vgg_architecture:
  value:
  - 64
  - 64
  - M
  - 128
  - 128
  - M
weight_decay:
  value: 0.0005
