wandb_version: 1

activation:
  value: gelu
batch_norm:
  value: true
batch_size:
  value: 32
dropout:
  value: 0.3
epochs:
  value: 20
learning_rate:
  value: 0.01
momentum:
  value: 0.9
num_classes:
  value: 10
optimizer:
  value: adam
seed:
  value: 42
vgg_architecture:
  value:
  - 64
  - 64
  - M
  - 128
  - 128
  - M
weight_decay:
  value: 0.0001
