wandb_version: 1

activation:
  value: relu
batch_norm:
  value: false
batch_size:
  value: 128
dropout:
  value: 0.5
epochs:
  value: 50
learning_rate:
  value: 0.1
momentum:
  value: 0.7
num_classes:
  value: 10
optimizer:
  value: sgd
vgg_architecture:
  value:
  - 64
  - 64
  - M
  - 128
  - 128
  - M
weight_decay:
  value: 1.0e-05
