wandb_version: 1

activation:
  value: tanh
batch_norm:
  value: false
batch_size:
  value: 128
dropout:
  value: 0.5
epochs:
  value: 50
learning_rate:
  value: 0.001
momentum:
  value: 0.5
num_classes:
  value: 10
optimizer:
  value: nesterov_sgd
vgg_architecture:
  value:
  - 64
  - 64
  - M
  - 128
  - 128
  - M
weight_decay:
  value: 0.0001
