wandb_version: 1

activation:
  value: silu
batch_norm:
  value: false
batch_size:
  value: 64
dropout:
  value: 0.3
epochs:
  value: 20
learning_rate:
  value: 0.001
momentum:
  value: 0.7
num_classes:
  value: 10
optimizer:
  value: rmsprop
vgg_architecture:
  value:
  - 64
  - 64
  - M
  - 128
  - 128
  - M
weight_decay:
  value: 0.0005
