wandb_version: 1

activation:
  value: sigmoid
batch_norm:
  value: true
batch_size:
  value: 256
dropout:
  value: 0.5
epochs:
  value: 30
learning_rate:
  value: 0.001
momentum:
  value: 0.9
num_classes:
  value: 10
optimizer:
  value: sgd
seed:
  value: 42
vgg_architecture:
  value:
  - 64
  - 64
  - M
  - 128
  - 128
  - M
weight_decay:
  value: 1.0e-05
