wandb_version: 1

activation:
  value: gelu
batch_norm:
  value: false
batch_size:
  value: 64
dropout:
  value: 0.4
epochs:
  value: 50
learning_rate:
  value: 0.0001
momentum:
  value: 0.5
num_classes:
  value: 10
optimizer:
  value: nadam
seed:
  value: 42
vgg_architecture:
  value:
  - 64
  - 64
  - M
  - 128
  - 128
  - M
weight_decay:
  value: 0.0005
