_wandb:
    value:
        cli_version: 0.22.2
        e:
            lbog0yvh7nkcyu7fucz154f5zdu8ek90:
                args:
                    - --sweep_id=l44wkssl
                    - --project=wandb_vgg_experiments
                    - --count=20
                codePath: trainer.py
                codePathLocal: trainer.py
                email: krishnaprasad.kps@gmail.com
                executable: C:\Users\DDA\AppData\Local\Programs\Python\Python311\python.exe
                host: DESKTOP-59ENVD4
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\DDA\Downloads\CS6886W-sweep\CS6886W-sweep\trainer.py
                python: CPython 3.11.9
                root: C:\Users\DDA\Downloads\CS6886W-sweep\CS6886W-sweep
                startedAt: "2025-10-18T08:43:58.201190Z"
                writerId: lbog0yvh7nkcyu7fucz154f5zdu8ek90
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 14
            "4": 3.11.9
            "5": 0.22.2
            "8":
                - 3
            "12": 0.22.2
            "13": windows-amd64
activation:
    value: relu
batch_norm:
    value: false
batch_size:
    value: 64
dropout:
    value: 0.4
epochs:
    value: 20
learning_rate:
    value: 0.1
momentum:
    value: 0.7
num_classes:
    value: 10
optimizer:
    value: adamgrad
vgg_architecture:
    value:
        - 64
        - 64
        - M
        - 128
        - 128
        - M
weight_decay:
    value: 0.0005
